Global variables implementation
logspace-ai/langflow pull request #1548
Opened 2024-03-21 14:36 UTC by lucaseduoli

This PR is related to the Global Variables functionality.

![image](https://github.com/logspace-ai/langflow/assets/62335616/0829db58-c26c-499f-9d59-c11fa0a1cf5b)
When clicking the Globe, it's possible to use global variables in any InputComponent.
When hovering an item, it's possible to delete it.
When clicking on Add New Variable, it's possible to add a new global variable.

2024-03-22 15:34 UTC, ogabrielluiz requested changes

2024-03-22 15:34 UTC, ogabrielluiz commented on langflow1.db
This should be removed

2024-03-22 15:34 UTC, ogabrielluiz commented on src/frontend/src/components/codeTabsComponent/index.tsx
> +                                                            title: `the value inserted in ${templateField} is a global variable, \n
This text could be improved

2024-03-22 16:19 UTC, lucaseduoli commented on langflow1.db
Resolved

2024-03-22 16:19 UTC, lucaseduoli commented on src/frontend/src/components/codeTabsComponent/index.tsx
> +                                                            title: `the value inserted in ${templateField} is a global variable, \n
Resolved

2024-03-22 16:27 UTC, ogabrielluiz approved these changes
LGTM

2024-03-25 20:00 UTC, anovazzi1 requested changes
Variable value and mark lost after update component code, need to clean the variable field or keep the variable as it was

2024-03-27 21:17 UTC, anovazzi1 approved these changes
LGTM

2024-03-27 21:24 UTC, merged