Add Scrollbar to Modal for Advanced Settings when Input Limit Exceeded
logspace-ai/langflow pull request #389
Opened 2023-05-28 22:07 UTC by Cristhianzl

Description:
This pull request proposes the addition of a scrollbar to the modal window containing advanced settings when the number of input fields exceeds the limit of the screen. This enhancement aims to improve user experience by providing a convenient way to access all settings, even when the available screen space is limited.
The number of inputs in the screen is limited by a variable on Utils that can be easily changed in the future if  It's needed.

2023-05-28 23:03 UTC, ogabrielluiz requested changes
When the user is allowed to scroll, the scrollbar should become visible.

2023-05-29 02:52 UTC, anovazzi1 reviewed
could you please tell the reference node with a scrolling issue to test this pr?

2023-05-29 02:52 UTC, anovazzi1 commented on src/frontend/src/modals/NodeModal/components/ModalField/index.tsx
I think we can make this last item pb-3 in a better way than iterating throw all the items every item to check if it's the last

2023-05-29 09:25 UTC, ogabrielluiz commented
> could you please tell the reference node with a scrolling issue to test this pr?

OpenAIEmbeddings

2023-05-29 14:07 UTC, anovazzi1 commented
tested locally and looks good, could apply some style on the sidebar, the same as the one in the chat input text-area
![image](https://github.com/logspace-ai/langflow/assets/70824914/ca8dc959-9f6d-4d14-bcf0-37eb943e010c)

2023-05-29 21:26 UTC, closed without merging