Types refactor
logspace-ai/langflow pull request #659
Opened 2023-07-19 20:07 UTC by igorrCarvalho

This pull request aims to perform a comprehensive type refactor across the project, enhancing type safety and improving code clarity. The changes introduced in this PR will lead to better maintainability, reduced bugs related to type-related issues, and increased overall code quality.

2023-07-25 13:25 UTC, lucaseduoli requested changes
Need to merge the DEV changes with the types refactor. Putting JSX.Element as the component types is not a good practice. Take FloatComponent as an example: you need to create a specific type to each of the components.

2023-07-25 19:41 UTC, anovazzi1 requested changes

2023-07-26 18:27 UTC, anovazzi1 requested changes

2023-07-26 18:27 UTC, anovazzi1 commented on src/frontend/src/modals/baseModal/index.tsx
improve the name of the type, it's the the header of the modal, so headerConst is not a good name

2023-07-26 18:27 UTC, anovazzi1 commented on src/frontend/src/pages/FlowPage/components/PageComponent/index.tsx
> +  const onSelectionChange = useCallback((flow): void => {
flow has any type here

2023-07-26 18:27 UTC, anovazzi1 commented on src/frontend/src/types/components/index.ts
> +  data: object;
object is not a good type practice, avoid using it

2023-07-26 18:27 UTC, anovazzi1 commented on src/frontend/src/types/flow/index.ts
> +  value: null;
value is always null?

2023-07-26 18:27 UTC, anovazzi1 commented on src/frontend/src/types/typesContext/index.ts
avoid using any as type

2023-08-16 21:39 UTC, merged