Fixed Lint error
logspace-ai/langflow pull request #918
Opened 2023-09-14 17:35 UTC by gyliu513

Fixed https://github.com/logspace-ai/langflow/issues/904

2023-09-14 20:38 UTC, ogabrielluiz requested changes
Thanks for the help!

2023-09-14 20:38 UTC, ogabrielluiz commented on src/backend/langflow/components/textsplitters/RecursiveCharacterTextSplitter.py
Thanks for the PR, @gyliu513!

Why not use this function?

2023-09-14 20:38 UTC, ogabrielluiz commented on src/backend/langflow/services/database/models/user/crud.py
Maybe `Optional[User]` would be better in this case?

I think the point of this is mainly that a user might not be found in a function that uses this other function.

2023-09-14 23:49 UTC, gyliu513 commented on src/backend/langflow/components/textsplitters/RecursiveCharacterTextSplitter.py
my bad, just found there is no implementation for this API.

Do you know if the implementation is deleted or just do not have this since the beginning?

2023-09-14 23:49 UTC, gyliu513 commented on src/backend/langflow/services/database/models/user/crud.py
Done

2023-09-15 00:29 UTC, ogabrielluiz commented on src/backend/langflow/components/textsplitters/RecursiveCharacterTextSplitter.py
That function is in `langflow.utils.util.build_loader_repr_from_documents`

2023-09-15 00:34 UTC, gyliu513 commented on src/backend/langflow/components/textsplitters/RecursiveCharacterTextSplitter.py
@ogabrielluiz I did not find the function at https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/utils/util.py , am I missing anything? Thanks

2023-09-15 00:35 UTC, merged

2023-09-15 00:36 UTC, gyliu513 commented on src/backend/langflow/components/textsplitters/RecursiveCharacterTextSplitter.py
I think I need to add it back if you can provide the content of this function :)